name: Test Simulator app

on:
    pull_request:

jobs:
    test:
        runs-on: macos-11
        strategy:
            matrix:
                xcode: ['13.1']
                device: ['iPhone 13']

        steps:
            - name: Switch Xcode version to ${{ matrix.xcode }}
              run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

            - name: Print simulators list
              run: xcrun simctl list --json

            - name: Force booting Simulator app
              run: xcrun simctl boot "${{ matrix.device }}"

            - name: Bring Simulator to the foreground
              # run: open -Fn /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer/Applications/Simulator.app
              run: open -a Simulator
